services:
    postgres:
        container_name: postgres
        image: postgres:16.2-alpine
        restart: always
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_ROOT_PASSWORD: ${POSTGRES_ROOT_PASSWORD}
        ports:
            - ${POSTGRES_PORT}:5432
        volumes:
            - ./db-data:/var/lib/postgresql/data
            # - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
